# ============================ FECHAS ============================ #

# FECHA Y HORA ACTUAL DEL SERVIDOR
SELECT NOW();

# FECHA ACTUAL DEL SERVIDOR
SELECT CURRENT_DATE();

# HORA ACTUAL DEL SERVIDOR
SELECT CURRENT_TIME();

# DIFERENCIA EN DÍAS ENTRE DOS FECHAS
SELECT DATEDIFF("2017-06-25", "2017-06-15");

# AÑADIR INTERVALOS A UNA FECHA Y HORA
SELECT DATE_ADD("2017-06-15 10:00:10", INTERVAL 5000 SECOND);

# EXTRAER PARTES DE UNA FECHA
SELECT DATE(NOW());

SELECT YEAR(NOW());
SELECT EXTRACT(YEAR FROM NOW());

SELECT QUARTER(NOW());
SELECT EXTRACT(QUARTER FROM NOW());

SELECT MONTH(NOW());
SELECT EXTRACT(MONTH FROM NOW());

SELECT WEEK(NOW()); # OJITO: LAS SEMANAS COMIENZAN EN DOMINGO
SELECT EXTRACT(WEEK FROM NOW());

SELECT DAY(NOW());
SELECT EXTRACT(DAY FROM NOW());

SELECT TIME(NOW());

SELECT HOUR(NOW());
SELECT EXTRACT(HOUR FROM NOW());

SELECT MINUTE(NOW());
SELECT EXTRACT(MINUTE FROM NOW());

SELECT SECOND(NOW());
SELECT EXTRACT(SECOND FROM NOW());

# FORMATEAR FECHAS
SELECT DATE_FORMAT(NOW(), "%y");


# ============================= EJERCICIOS ============================= #


# EJ1 - ¿CUÁNTOS DÍAS HAS VIVIDO?
SELECT DATEDIFF(NOW(), "1995-12-07");

# EJ2 - ¿CUÁNTAS HORAS HAS VIVIDO?
SELECT DATEDIFF(NOW(), "1995-12-07")*24;

# EJ3 - ¿QUÉ DÍA DE LA SEMANA NACISTE?
SELECT DAYNAME("1995-12-07");
SELECT DATE_FORMAT("1995-12-07", "%W");

# EJ4 - ¿QUÉ EDAD TENÍAS EL 1 DE ENERO DEL AÑO 2000?
SELECT FLOOR(DATEDIFF("2000-01-01", "1995-12-07")/365);

# EJ5 - ¿EN QUÉ FECHA ESTAREMOS DENTRO DE 7000 HORAS?
SELECT DATE_ADD(NOW(), INTERVAL 7000 HOUR);

# EJ6 - ¿EN QUÉ FECHA DUPLICARÁS TU EDAD ACTUAL?

SELECT DATE_ADD(NOW(), INTERVAL (DATEDIFF(NOW(), "1995-12-07")) DAY);

# EJ7 - MUESTRA LOS DÍAS QUE HAN ALQUILADO LAS PELÍCULAS (RENTAL)
SELECT 
	RENTAL_ID,
	RENTAL_DATE,
    RETURN_DATE,
    DATEDIFF(RETURN_DATE, RENTAL_DATE) AS DIAS_ALQUILER
FROM RENTAL;

# EJ8 - MUESTRA UNA LISTA DE LOS TÍTULOS DE LAS PELÍCULAS Y CUÁNTOS DÍAS DE MEDIA SE HAN ALQUILADO

SELECT 
	FILM.TITLE,
    AVG(DATEDIFF(RETURN_DATE, RENTAL_DATE)) AS DIAS_ALQUILER_PROMEDIOS
FROM RENTAL RENT
JOIN INVENTORY INV ON RENT.INVENTORY_ID=INV.INVENTORY_ID
JOIN FILM ON INV.FILM_ID=FILM.FILM_ID
GROUP BY FILM.FILM_ID;

# EJ9 - MUESTRA UNA LISTA CON EL ID DEL ALQUILER, EL NOMBRE COMPLETO DEL CLIENTE, EL NOMBRE DE LA PELÍCULA Y CUÁNTAS VECES HA PODIDO VER LA PELÍCULA EN ESOS DÍAS

SELECT 
	RENT.RENTAL_ID,
    CONCAT (CUST.FIRST_NAME, " ", CUST.LAST_NAME) AS CUSTOMER,
    FILM.TITLE,
    DATEDIFF(RETURN_DATE, RENTAL_DATE)*24*60 / FILM.LENGTH AS VECES_PUEDE_VER
FROM RENTAL RENT
JOIN INVENTORY INV ON RENT.INVENTORY_ID=INV.INVENTORY_ID
JOIN FILM ON INV.FILM_ID=FILM.FILM_ID
JOIN CUSTOMER CUST ON RENT.CUSTOMER_ID=CUST.CUSTOMER_ID;

# EJ10 - MUESTRA UNA LISTA DE LOS CLIENTES Y EL TOTAL DE DÍAS QUE HAN TENIDO PELÍCULAS ALQUILADAS

SELECT 
	CONCAT(CUST.FIRST_NAME, " ", CUST.LAST_NAME) AS CLIENTE,
    SUM(DATEDIFF(RETURN_DATE, RENTAL_DATE)) AS DIAS_ALQUILER_TOTAL
FROM RENTAL RENT
JOIN CUSTOMER CUST ON RENT.CUSTOMER_ID=CUST.CUSTOMER_ID
GROUP BY CUST.CUSTOMER_ID;

# EJ11 - MUESTRA UNA LISTA CON EL ID DEL ALQUILER, EL NOMBRE COMPLETO DEL CLIENTE, EL NOMBRE DE LA PELÍCULA, LA FECHA DE ALQUILER, LA FECHA DE DEVOLUCIÓN Y LA FECHA DE PAGO (SOLO FECHA EN TODOS LOS CASOS)

SELECT 
	RENT.RENTAL_ID,
    CONCAT(CUST.FIRST_NAME, " ", CUST.LAST_NAME) AS CLIENTE,
    FILM.TITLE AS PELÍCULA,
    DATE(RENTAL_DATE) AS FECHA_ALQUILER,
    DATE(RETURN_DATE) AS FECHA_DEVOLUCION,
    DATE(PAYMENT_DATE) AS FECHA_PAGO
FROM RENTAL RENT
JOIN INVENTORY INV ON RENT.INVENTORY_ID=INV.INVENTORY_ID
JOIN FILM ON INV.FILM_ID=FILM.FILM_ID
JOIN CUSTOMER CUST ON RENT.CUSTOMER_ID=CUST.CUSTOMER_ID
JOIN PAYMENT PAY ON RENT.RENTAL_ID=PAY.RENTAL_ID;

# EJ12 - ¿CUÁNTAS PELÍCULAS SE HAN ALQUILADO ENTRE LAS 12 DE LA NOCHE Y LAS 6 DE LA MAÑANA?

SELECT
	COUNT(*) AS PELÍCULAS_CON_NOCTURNIDAD
FROM RENTAL
WHERE TIME(RENTAL_DATE)>="00:00:00" AND TIME(RENTAL_DATE)<"06:00:00"; #00:00:00 - 05:59:59
# WHERE HOUR(RENTAL_DATE)>=0 AND HOUR(RENTAL_DATE)<=5; #00:00:00 - 05:59:59
# WHERE HOUR(RENTAL_DATE) BETWEEN 0 AND 5; #00:00:00 - 05:59:59

# ============================= ALGUNAS FUNCIONES AVANZADAS ============================= #

USE WORLD;

# FUNCIÓN IF
# La función IF() devuelve un valor si una condición es TRUE, u otro valor si una condición es FALSE.
SELECT IF(500<1000, "YES", "NO");

# FUNCIÓN IFNULL
# La función IFNULL(EXPRESIÓN, VALOR_ALTERNATIVO) devuelve un valor especificado si la expresión es NULL. Si la expresión NO es NULL, esta función devuelve la expresión.

SELECT IFNULL(NULL, "VALOR NULO");

# FUNCIÓN COALESCE
# DEVUELVE EL PRIMER VALOR NO NULO

SELECT COALESCE(NULL, NULL, NULL, 'VALOR', NULL, 'OTRO VALOR');

SELECT 
	NAME,INDEPYEAR, GNPOLD, LOCALNAME,
	COALESCE(INDEPYEAR, GNPOLD, LOCALNAME)
FROM COUNTRY;

SELECT 
	NAME,
    INDEPYEAR,
    IFNULL(INDEPYEAR, 0),
    COALESCE(INDEPYEAR, 0), #IGUAL FUNCIONAMIENTO CON LA FUNCIÓN COALESCE
    IF(INDEPYEAR IS NULL, 0, INDEPYEAR) #IGUAL FUNCIONAMIENTO CON LA FUNCIÓN IF
FROM COUNTRY;

# FUNCIÓN CASE
#La sentencia CASE recorre las condiciones y devuelve un valor cuando se cumple la primera condición (como una sentencia IF-THEN-ELSE). Así, una vez que una condición es verdadera, dejará de leer y devolverá el resultado. Si no se cumple ninguna condición, devolverá el valor de la cláusula ELSE. Si no hay ninguna parte ELSE y ninguna condición es verdadera, devuelve NULL.

SELECT 
	NAME,
    POPULATION,
	CASE
		WHEN POPULATION BETWEEN 100000 AND 1000000 THEN "PAÍS PEQUEÑO"
		WHEN POPULATION BETWEEN 1000000 AND 10000000 THEN "PAÍS MEDIANO"
		WHEN POPULATION > 10000000 THEN "PAÍS GRANDE"
		ELSE "PAÍS MINÚSCULO"
	END AS TAMAÑO
FROM COUNTRY;

# ============================= MÁS EJERCICIOS ============================= #

# EJ13 - MUESTRA LA CANTIDAD DE SINIESTROS QUE HAN OCURRIDO PARA CADA DÍA DE LA SEMANA. ORDENA DE MAYOR A MENOR.

SELECT
    DATE_FORMAT(FECHA, "%W") AS DÍA_SEMANA,
    COUNT(*) AS SINIESTROS
FROM SINIESTRO
GROUP BY DÍA_SEMANA
ORDER BY SINIESTROS DESC;

# EJ14 - MUESTRA SOLO LOS CLIENTES QUE LLEVEN MÁS DE UN AÑO CON EL PERMISO DE CONDUCIR

SELECT * 
FROM CLIENTE
WHERE FECHA_PERMISO < DATE_ADD(NOW(), INTERVAL -1 YEAR); #LA FECHA DE HOY MENOS UN AÑO

# EJ15 - MUESTRA SOLO LOS CLIENTES QUE LLEVEN MÁS DE UN AÑO CON EL PERMISO DE CONDUCIR Y TIENEN MÁS DE 25 AÑOS.

SELECT * 
FROM CLIENTE
WHERE FECHA_PERMISO < DATE_ADD(NOW(), INTERVAL -1 YEAR)
AND FECHA_NACIMIENTO < DATE_ADD(NOW(), INTERVAL -25 YEAR);

# EJ16 - ¿HAY ALGÚN CLIENTE CUYA FECHA DE NACIMIENTO SEA POSTERIOR A LA FECHA DE MATRICULACIÓN DE SU VEHÍCULO?

SELECT 
	NOMBRE,
    FECHA_NACIMIENTO,
    FECHA_1_MATRICULACION
FROM CLIENTE CLI
JOIN CLIENTE_ASEGURA_VEHICULO CAV ON CLI.DNI=CAV.DNI_CLIENTE
JOIN VEHICULO V ON CAV.NUMERO_BASTIDOR_VEHICULO=V.NUMERO_BASTIDOR
WHERE FECHA_NACIMIENTO>FECHA_1_MATRICULACION;

# EJ17 - MUESTRA LA TABLA DE CLIENTES COMPLETA Y AÑADE UNA COLUMNA BOOLEANA QUE INDIQUE SI EL CLIENTE ERA MAYOR DE EDAD O NO CUANDO SE SACÓ EL PERMISO.

SELECT 
	*,
    FECHA_PERMISO > DATE_ADD(FECHA_NACIMIENTO, INTERVAL 18 YEAR) AS MAYOR_EDAD
FROM CLIENTE;

# EJ18 - MUESTRA LA TABLA DE CLIENTES COMPLETA Y AÑADE UNA COLUMNA QUE INDIQUE: La Organización Mundial de la Salud (OMS), por su parte, clasifica la edad adulta de la siguiente manera: adulto joven, de 18 a 44 años; adulto medio, de 45 a 59 años; adulto mayor (o anciano joven), de 60 a 74 años; anciano, de 75 a 90 años; y anciano longevo, a partir de los 90 años.

SELECT 
	NOMBRE,
    FECHA_NACIMIENTO,
    FLOOR(DATEDIFF(NOW(), FECHA_NACIMIENTO)/365) AS EDAD,
	CASE
		WHEN FLOOR(DATEDIFF(NOW(), FECHA_NACIMIENTO)/365) BETWEEN 18 AND 44 THEN "ADULTO JOVEN"
		WHEN FLOOR(DATEDIFF(NOW(), FECHA_NACIMIENTO)/365) BETWEEN 45 AND 59 THEN "ADULTO MEDIO"
        WHEN FLOOR(DATEDIFF(NOW(), FECHA_NACIMIENTO)/365) BETWEEN 60 AND 74 THEN "ANCIANO JOVEN"
        WHEN FLOOR(DATEDIFF(NOW(), FECHA_NACIMIENTO)/365) BETWEEN 75 AND 90 THEN "ANCIANO"
        WHEN FLOOR(DATEDIFF(NOW(), FECHA_NACIMIENTO)/365) > 90 THEN "ANCIANO LONGEVO"
		ELSE "NO ADULTO"
	END AS EDAD_CLASIFICACION
FROM CLIENTE;

# EJ19 - MUESTRA LA TABLA DE CLIENTES COMPLETA Y AÑADE UNA COLUMNA QUE INDIQUE "CONDUCTOR TARDÍO" SI EL CLIENTE TARDÓ MÁS DE 10 AÑOS TRAS SU MAYORÍA DE EDAD EN OBTENER EL PERMISO DE CONDUCIR O "CONDUCTOR PRECOZ" EN CASO CONTRARIO.

SELECT
	*,
    IF(FECHA_PERMISO > DATE_ADD(FECHA_NACIMIENTO, INTERVAL 18+10 YEAR), 
       "CONDUCTOR TARDÍO", 
       "CONDUCTOR PRECOZ")
FROM CLIENTE;

# EJ20 - MUESTRA LA TABLA DE SINIESTROS COMPLETA PERO AÑADIENDO UNA COLUMNA BOOLEANA QUE INDIQUE SI EL SINIESTRO OCURRIÓ EN FIN DE SEMANA O NO.

SELECT 
	*,
    DATE_FORMAT(FECHA, "%W") AS DÍA_SEMANA,
    DATE_FORMAT(FECHA, "%W") IN ("SATURDAY", "SUNDAY") AS EN_FIN_DE_SEMANA
FROM SINIESTRO;

# EJ21 - MUESTRA EL NOMBRE DE LOS PAÍSES Y SU ESPERANZA DE VIDA. PARA LOS PAÍSES SIN ESPERANZA DE VIDA, MUESTRA LA MEDIA DE ESPERANZA DE VIDA MUNDIAL.

USE WORLD;

SELECT
	NAME,
    LIFEEXPECTANCY,
    IF(LIFEEXPECTANCY IS NULL, (SELECT AVG(LIFEEXPECTANCY) FROM COUNTRY), LIFEEXPECTANCY),
    IFNULL(LIFEEXPECTANCY, (SELECT AVG(LIFEEXPECTANCY) FROM COUNTRY))
FROM COUNTRY;

# EJ22 - MUESTRA EL NOMBRE DE LOS PAÍSES, SU AÑO DE INDEPENDENCIA Y UNA COLUMNA QUE INDIQUE "DESCOLONIZACIÓN" SI LA FECHA DE INDEPENDENCIA ES POSTERIOR O IGUAL A 1945 O "-" EN CASO CONTRARIO.

SELECT
	NAME,
    INDEPYEAR,
    IF(INDEPYEAR>=1945, "DESCOLONIZACIÓN", "-")
FROM COUNTRY;