DROP SCHEMA IF EXISTS SEGUROS;
CREATE SCHEMA SEGUROS;
USE SEGUROS;

CREATE TABLE CLIENTE(
	DNI CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50),
    FECHA_NACIMIENTO DATE,
    FECHA_PERMISO DATE,
    
    CONSTRAINT DNI_VALIDO CHECK (DNI RLIKE "[0-9]{8}[A-Z]")
);

CREATE TABLE VEHICULO(
	NUM_BASTIDOR CHAR(17) PRIMARY KEY,
    MATRICULA CHAR(7),
    MARCA VARCHAR(50),
    MODELO VARCHAR(50),
    COLOR VARCHAR(20),
    FECHA_1A_MATRICULA DATE,
    
    CONSTRAINT MATRICULA_VALIDA CHECK (MATRICULA RLIKE "[0-9]{4}[BCDFGHJKLMNPQRSTVWXYZ]{3}") 
);

CREATE TABLE CLIENTE_ASEGURA_VEHICULO(
	DNI_CLIENTE CHAR(9),
    NUM_BASTIDOR_VEHICULO CHAR(17),
    
    PRIMARY KEY (DNI_CLIENTE,NUM_BASTIDOR_VEHICULO),
    FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI),
    FOREIGN KEY (NUM_BASTIDOR_VEHICULO) REFERENCES VEHICULO(NUM_BASTIDOR)
);


CREATE TABLE POLIZA(
	NUMERO INT PRIMARY KEY,
    PRECIO DECIMAL(7,2),
    DNI_CLIENTE CHAR(9),
    NUM_BASTIDOR_VEHICULO CHAR(17),
    
    FOREIGN KEY (DNI_CLIENTE,NUM_BASTIDOR_VEHICULO) REFERENCES CLIENTE_ASEGURA_VEHICULO(DNI_CLIENTE,NUM_BASTIDOR_VEHICULO),
    CONSTRAINT PRECIO_VALIDO CHECK (PRECIO > 0)
);

CREATE TABLE COBERTURA(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    TIPO VARCHAR(50),
    CUANTIA DECIMAL(7,2),
    
    CONSTRAINT CUANTIA_VALIDA_COBERTURA CHECK (CUANTIA > 0)
);
CREATE TABLE SINIESTRO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE,
    LUGAR VARCHAR(50),
    CAUSA VARCHAR(50),
    CUANTIA DECIMAL(7,2),
    NUM_POLIZA INT,
    
    FOREIGN KEY (NUM_POLIZA) REFERENCES POLIZA(NUMERO),
    CONSTRAINT CUANTIA_VALIDA_SINIESTRO CHECK (CUANTIA > 0)
);

CREATE TABLE POLIZA_ASOCIA_COBERTURA(
	NUM_POLIZA INT,
    ID_COBERTURA INT,
    
    PRIMARY KEY(NUM_POLIZA,ID_COBERTURA),
    FOREIGN KEY (NUM_POLIZA) REFERENCES POLIZA(NUMERO),
    FOREIGN KEY (ID_COBERTURA) REFERENCES COBERTURA(ID)
);