DROP SCHEMA IF EXISTS VUELTA_CICLISTA; #PARA IR PROBANDO LA BASE, LA BORRA SI EXISTE Y SI NO SE CREA.
CREATE SCHEMA VUELTA_CICLISTA;
USE VUELTA_CICLISTA;

CREATE TABLE CICLISTA(
	DNI CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    NACIONALIDAD VARCHAR(40),
    FECHA_NACIMIENTO DATE
);

CREATE TABLE EQUIPO(
	NOMBRE VARCHAR(40) PRIMARY KEY,
    NACIONALIDAD VARCHAR(50),
    DIRECTOR VARCHAR(30)
);

CREATE TABLE PRUEBA(
	NOMBRE VARCHAR(40),
    ANIO SMALLINT,
    NUMERO_ETAPAS TINYINT,
    KM_TOTALES SMALLINT, #DECIMAL(6,2) PUEDE SER TAMBIÉN OTRA OPCIÓN.
    DNI_GANADOR CHAR(9),
    
    PRIMARY KEY(NOMBRE,ANIO),
    FOREIGN KEY(DNI_GANADOR) REFERENCES CICLISTA(DNI)
);

CREATE TABLE CICLISTA_PERTENECE_EQUIPO(
	DNI_CICLISTA CHAR(9),
    NOMBRE_EQUIPO VARCHAR(40),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    
    PRIMARY KEY (DNI_CICLISTA,NOMBRE_EQUIPO,FECHA_INICIO),
    FOREIGN KEY (DNI_CICLISTA) REFERENCES CICLISTA(DNI),
    FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES EQUIPO(NOMBRE)
);

CREATE TABLE EQUIPO_PARTICIPA_PRUEBA(
	NOMBRE_EQUIPO VARCHAR(40),
    NOMBRE_PRUEBA VARCHAR(40),
    ANIO_PRUEBA SMALLINT,
    PUESTO SMALLINT,
    
    PRIMARY KEY (NOMBRE_EQUIPO, NOMBRE_PRUEBA, ANIO_PRUEBA),
    FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES EQUIPO(NOMBRE),
    FOREIGN KEY (NOMBRE_PRUEBA, ANIO_PRUEBA) REFERENCES PRUEBA(NOMBRE, ANIO)
);

#================================================= INSERTAR DATOS =============================================================#

INSERT INTO CICLISTA VALUES
("12345678A", "FULANO", "ESPAÑOLA", "2000-07-07"),
("12366778Z", "MENGALO", "FRANCESA", "2002-05-30"),
("98655778B", "FIRHANO", "SUECA", "2004-06-15");

INSERT INTO EQUIPO VALUES
("ALPINE", "SUIZA", "SWISHEECSK");

INSERT INTO PRUEBA VALUES
("VUELTA EUROPA", 2001, 40, 5140, NULL),
("VUELTA AMERICA", 2002, 47, 6050, "98655778B");

INSERT INTO CICLISTA_PERTENECE_EQUIPO VALUES
("98655778B", "ALPINE", "2008-03-02", "2012-03-02");

INSERT INTO EQUIPO_PARTICIPA_PRUEBA VALUES
("ALPINE", "VUELTA EUROPA", "2001", 1);

SELECT * FROM CICLISTA; # SELECCIONA TODA LA TABLA ESCRIBIENDO EL '*'.
SELECT * FROM EQUIPO;
SELECT * FROM PRUEBA;
SELECT * FROM CICLISTA_PERTENECE_EQUIPO;
SELECT * FROM EQUIPO_PARTICIPA_PRUEBA;