DROP SCHEMA IF EXISTS ANUNCIOS_WEB;
CREATE SCHEMA ANUNCIOS_WEB;
USE ANUNCIOS_WEB;

CREATE TABLE CLIENTE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(100),
    TELEFONO VARCHAR(15) UNIQUE,
    EMAIL VARCHAR(100) UNIQUE
);

CREATE TABLE ANUNCIO(
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    TIPO VARCHAR(30),
    TITULO VARCHAR(50),
    CONTENIDO MEDIUMTEXT, # DEFAULT "CONTENIDO MARCA ACME",
    CATEGORIA VARCHAR(30),
    PRECIO DECIMAL(9,2),
    ID_CLIENTE INT,
    
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    
    CONSTRAINT PRECIO_MINIMO CHECK (PRECIO>0)
);

CREATE TABLE WEB(
	URL VARCHAR(255) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    TOPICO VARCHAR(100)
);

CREATE TABLE ANUNCIO_APARECE_WEB(
	CODIGO_ANUNCIO INT,
    URL_WEB VARCHAR(255),
    FECHA_INICIO DATETIME, 
    FECHA_FIN DATETIME,
    
    PRIMARY KEY (CODIGO_ANUNCIO, URL_WEB, FECHA_INICIO),
    FOREIGN KEY (CODIGO_ANUNCIO) REFERENCES ANUNCIO(CODIGO),
    FOREIGN KEY (URL_WEB) REFERENCES WEB(URL),
    
    CONSTRAINT FECHA_CORRECTA CHECK (FECHA_FIN>FECHA_INICIO)
);