DROP SCHEMA IF EXISTS ASIGNATURAS;
CREATE SCHEMA ASIGNATURAS;
USE ASIGNATURAS;

CREATE TABLE PROFESOR(
	NRP INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50), 
    AREA_CONOCIMIENTO VARCHAR(100), 
    CATEGORIA VARCHAR(100),
    ID_DEPARTAMENTO INT
);
        
CREATE TABLE DEPARTAMENTO(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NRP_DIRECTOR INT,
    
    FOREIGN KEY (NRP_DIRECTOR) REFERENCES PROFESOR(NRP)
);

# ALTER TABLE PROFESOR ADD COLUMN ID_DEPARTAMENTO INT; (Si ya se ha añadido la columna en la tabla PROFESOR arriba no hace falta poner esto)
ALTER TABLE PROFESOR ADD FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID);

CREATE TABLE GRUPO(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    MAX_ALUMNOS SMALLINT, 
    TIPO VARCHAR(50)
);

CREATE TABLE GRUPO_TEORIA(
	ID_TEORIA INT PRIMARY KEY, 
    HORAS_CLASE TIME,
    
    FOREIGN KEY (ID_TEORIA) REFERENCES GRUPO(ID)
);

CREATE TABLE GRUPO_PRACTICA(
	ID_PRACTICA INT PRIMARY KEY, 
    TALLER VARCHAR(50),
    
    FOREIGN KEY (ID_PRACTICA) REFERENCES GRUPO(ID)
);

CREATE TABLE ALUMNO(
	DNI CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50), 
    FECHA_NACIMIENTO DATE, 
    BECA VARCHAR(50),
    
    CONSTRAINT DNI_VALIDO CHECK (DNI RLIKE "[0-9]{8}[A-Z]")
);

CREATE TABLE ASIGNATURA(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50), 
    CREDITOS SMALLINT, 
    CARACTER CHAR(1), 
    CURSO TINYINT
);

CREATE TABLE PROFESOR_IMPARTE_GRUPO(
	NRP_PROFESOR INT, 
    ID_GRUPO INT,
    
    PRIMARY KEY (NRP_PROFESOR, ID_GRUPO),
    FOREIGN KEY (NRP_PROFESOR) REFERENCES PROFESOR(NRP),
    FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID)
);

CREATE TABLE GRUPO_CONTIENE_ASIGNATURA(
	ID_GRUPO INT, 
    ID_ASIGNATURA INT,
    
    PRIMARY KEY (ID_GRUPO,ID_ASIGNATURA),
    FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID),
    FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA(ID)
);

CREATE TABLE MATRICULA(
	DNI_ALUMNO CHAR(9),
    ID_GRUPO INT,
    ID_ASIGNATURA INT,
    
    PRIMARY KEY (DNI_ALUMNO,ID_GRUPO,ID_ASIGNATURA),
    FOREIGN KEY (DNI_ALUMNO) REFERENCES ALUMNO(DNI),
    FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID),
    FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA(ID)
);