DROP SCHEMA IF EXISTS AEROPUERTO;
CREATE SCHEMA AEROPUERTO;
USE AEROPUERTO;

CREATE TABLE AEROPUERTO(
	ID CHAR(3) PRIMARY KEY,
    NOMBRE VARCHAR(100) UNIQUE NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
    PAIS VARCHAR(100) NOT NULL
);

INSERT INTO AEROPUERTO VALUES
("JH2","AEROPUERTO GRANADA/JAEN","GRANADA","ESPAÑA"),
("HP1", "AEROPUERTO DE MARACENA", "GRANADA","ESPAÑA"),
("PL3", "AEROPUERTO DE LUGO","GRANADA","ESPAÑA");

SELECT*FROM AEROPUERTO;

CREATE TABLE PROGRAMA_VUELO(
	COMPANIA VARCHAR(100),
    RUTA VARCHAR(200),
    ID_DESPEGUE_AEROPUERTO CHAR(3) NOT NULL,
    ID_ATERRIZAJE_AEROPUERTO CHAR(3) NOT NULL,
    
    PRIMARY KEY (COMPANIA,RUTA),
    FOREIGN KEY (ID_DESPEGUE_AEROPUERTO) REFERENCES AEROPUERTO(ID),
    FOREIGN KEY (ID_ATERRIZAJE_AEROPUERTO) REFERENCES AEROPUERTO(ID)
);

INSERT INTO PROGRAMA_VUELO VALUES 
("RYANAIR","LUGO, TOLEDO, MARACENA","PL3","HP1");

SELECT*FROM PROGRAMA_VUELO;

CREATE TABLE MODELO_AVION(
	NOMBRE VARCHAR(100) PRIMARY KEY,
    CAPACIDAD SMALLINT NOT NULL,
    
    CONSTRAINT LIMITACION_CAPACIDAD CHECK (CAPACIDAD BETWEEN 2 AND 200)
);

INSERT INTO MODELO_AVION VALUES
("FOMBO 3000","169");

SELECT*FROM MODELO_AVION;

CREATE TABLE VUELO(
	NUMERO_VUELO INT PRIMARY KEY,
    FECHA DATE NOT NULL,
    PLAZAS_VACIAS SMALLINT DEFAULT(10) NOT NULL,
    NOMBRE_MODELO_AVION VARCHAR(100) NOT NULL,
    COMPANIA_PROGRAMA_VUELO VARCHAR(100) NOT NULL,
    RUTA_PROGRAMA_VUELO VARCHAR(200) NOT NULL,
    
    FOREIGN KEY (NOMBRE_MODELO_AVION) REFERENCES MODELO_AVION(NOMBRE),
    FOREIGN KEY (COMPANIA_PROGRAMA_VUELO,RUTA_PROGRAMA_VUELO) REFERENCES PROGRAMA_VUELO(COMPANIA,RUTA),
    CONSTRAINT FECHA_VUELO_MINIMA CHECK (FECHA >= "1930-01-01")
);

INSERT INTO VUELO VALUES
("6969","2023-12-29","25","FOMBO 3000","RYANAIR","LUGO, TOLEDO, MARACENA");

CREATE TABLE MODELO_AVION_PUEDE_ATERRIZAR_AEROPUERTO(
	NOMBRE_MODELO_AVION VARCHAR(100),
    ID_AEROPUERTO CHAR(3) NOT NULL,
    
    PRIMARY KEY (NOMBRE_MODELO_AVION,ID_AEROPUERTO),
    FOREIGN KEY (NOMBRE_MODELO_AVION) REFERENCES MODELO_AVION(NOMBRE),
    FOREIGN KEY (ID_AEROPUERTO) REFERENCES AEROPUERTO(ID)
);

CREATE TABLE PROGRAMA_VUELO_TIENE_DIAS(
	COMPANIA_PROGRAMA_VUELO VARCHAR(100),
    RUTA_PROGRAMA_VUELO VARCHAR(200),
    NOMBRE_DIA VARCHAR(9) NOT NULL,
    
    PRIMARY KEY (COMPANIA_PROGRAMA_VUELO,RUTA_PROGRAMA_VUELO,NOMBRE_DIA),
    FOREIGN KEY (COMPANIA_PROGRAMA_VUELO,RUTA_PROGRAMA_VUELO) REFERENCES PROGRAMA_VUELO(COMPANIA,RUTA),
    CONSTRAINT LIMITACION_DIAS_SEMANA CHECK (NOMBRE_DIA IN ("LUNES","MARTES","MIERCOLES","JUEVES","VIERNES","SABADO","DOMINGO"))
    #CONSTRAINT LIMITACION_DIAS_SEMANA CHECK (NOMBRE_DIA="LUNES" OR "MARTES" OR "MIERCOLES" OR "JUEVES" OR "VIERNES" OR "SABADO" OR "DOMINGO")
);
