DROP SCHEMA IF EXISTS DEPARTAMENTOS;
CREATE SCHEMA DEPARTAMENTOS;
USE DEPARTAMENTOS;

CREATE TABLE EMPLEADO(
	DNI CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50),
    FECHA_NACIMIENTO DATE,
    SALARIO DECIMAL(7,2)
);

CREATE TABLE DEPARTAMENTO(
	NOMBRE VARCHAR(50) PRIMARY KEY,
    UBICACION VARCHAR(50),
    PRESUPUESTO DECIMAL(9,2),
    DNI_JEFE INT,
    
    FOREIGN KEY  (DNI_JEFE) REFERENCES EMPLEADO(DNI)
);

CREATE TABLE PROYECTO(
	NOMBRE VARCHAR(50) PRIMARY KEY,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    PRESUPUESTO DECIMAL(9,2),
    DESCRIPCION MEDIUMTEXT
);

CREATE TABLE DEPARTAMENTO_DIRIGE_PROYECTO(
	NOMBRE_DEPARTAMENTO,
    NOMBRE_PROYECTO,
    
    PRIMARY KEY (NOMBRE_DEPARTAMENTO,NOMBRE_PROYECTO),
    FOREIGN KEY (NOMBRE_DEPARTAMENTO) REFERENCES DEPARTAMENTO(NOMBRE),
    FOREIGN KEY (NOMBRE_PROYECTO) REFERENCES PROYECTO(NOMBRE)
);

CREATE TABLE EMPLEADO_MONITORIZA_DEPARTAMENTO_DIRIGE_PROYECTO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    DNI_EMPLEADO CHAR(9),
    NOMBRE_DEPARTAMENTO VARCHAR(50),
    NOMBRE_PROYECTO VARCHAR(50),
    FECHA_INICIO_MONITORIZA DATE,
    FECHA_FIN_MONITORIZA DATE,
    
    UNIQUE (DNI_EMPLEADO,NOMBRE_DEPARTAMENTO,NOMBRE_PROYECTO,FECHA_INICIO_MONITORIZA),
    FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI),
    FOREIGN KEY (NOMBRE_DEPARTAMENTO,NOMBRE_PROYECTO) REFERENCES DEPARTAMENTO_DIRIGE_PROYECTO(NOMBRE_DEPARTAMENTO,NOMBRE_PROYECTO)
);