DROP SCHEMA IF EXISTS PROYECTOS;
CREATE SCHEMA PROYECTOS;
USE PROYECTOS;

CREATE TABLE SEDE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    CIUDAD VARCHAR(50) NOT NULL,
    PAIS VARCHAR(50) NOT NULL, 
    DIRECCION VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) UNIQUE NOT NULL,
    DIRECTOR VARCHAR(50)
);

CREATE TABLE PROYECTO(
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    PRESUPUESTO  DECIMAL(9,2),
    RESPONSABLE VARCHAR(50),
    ID_SEDE INT,
    
    FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID),
    
    CONSTRAINT FECHA_FIN_POSTERIOR CHECK (FECHA_FIN>FECHA_INICIO)
);

CREATE TABLE POBLACION(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    PAIS VARCHAR(50),
    NUMERO_HABITANTES INT
);

CREATE TABLE ACTUACION (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION MEDIUMTEXT,
    INVERSION DECIMAL(9,2),
    CODIGO_PROYECTO INT,
    ID_POBLACION INT,
    
    FOREIGN KEY (CODIGO_PROYECTO) REFERENCES PROYECTO(CODIGO),
    FOREIGN KEY (ID_POBLACION) REFERENCES POBLACION(ID)
);

#=============RESTRICCIONES==============#

# UNIQUE -> SIN REPETIDOS
# NOT NULL -> NO PUEDE HABER NULO, SI O SI HAY QUE INCLUIR ALGO
# DEFAULT {VALOR} -> ESTABLECER VALOR PREDETERMINADO

INSERT INTO SEDE VALUES
(DEFAULT, "ESPAÑA", "GRANADA", "CALLE 1B", "7832998", "ALFONSO CAÑAS");

SELECT*FROM SEDE;

INSERT INTO PROYECTO VALUES
(DEFAULT, "TITULO", "2022-03-24", "2023-03-24", "203333.23", "ALFONSO CAÑAS", 1);

SELECT*FROM PROYECTO