DROP SCHEMA IF EXISTS CONCESIONARIO;
CREATE SCHEMA CONCESIONARIO;
USE CONCESIONARIO;

CREATE TABLE  MARCA(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50)
);

CREATE TABLE MODELO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    ID_MARCA INT,
    
    FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID)
);

CREATE TABLE VERSION(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    POTENCIA SMALLINT,
    PRECIO MEDIUMINT,
    COMBUSTIBLE VARCHAR(20),
    ID_MODELO INT,
    
    FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID)
);

CREATE TABLE EXTRA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    DESCRIPCION MEDIUMTEXT
);

CREATE TABLE CLIENTE(
	NIF CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    DIRECCION VARCHAR(50),
    TELEFONO CHAR(9)
);

CREATE TABLE VENDEDOR(
	NIF CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    DIRECCION VARCHAR(50),
    TELEFONO CHAR(9)
);

CREATE TABLE VERSION_EQUIPA_EXTRA(
	ID_VERSION INT,
    ID_EXTRA INT,
    PRECIO MEDIUMINT,
    
    PRIMARY KEY (ID_VERSION,ID_EXTRA),
    FOREIGN KEY (ID_VERSION) REFERENCES VERSION(ID),
    FOREIGN KEY (ID_EXTRA) REFERENCES EXTRA(ID)
);

CREATE TABLE CLIENTE_COMPRA_MODELO(
	NIF_CLIENTE CHAR(9),
    ID_MODELO INT,
    MATRICULA CHAR(7),
    FECHA_COMPRA DATE,
    NIF_VENDEDOR CHAR(9),
    
    PRIMARY KEY (NIF_CLIENTE,ID_MODELO,MATRICULA),
    FOREIGN KEY (NIF_CLIENTE) REFERENCES CLIENTE(NIF),
	FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID),
    FOREIGN KEY (NIF_VENDEDOR) REFERENCES VENDEDOR(NIF)
);