DROP SCHEMA IF EXISTS CARRERAS;
CREATE SCHEMA CARRERAS;
USE CARRERAS;

CREATE TABLE PARTICIPANTE(
	DNI CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50)
);

INSERT INTO PARTICIPANTE VALUES
("56462131N","ENCARNA"),
("52162131J","FRANCISCO");

CREATE TABLE ORGANIZADOR(
	DNI CHAR(9) PRIMARY KEY, 
    NOMBRE VARCHAR(50), 
    EDAD TINYINT, 
    CARGO VARCHAR(50), 
    FECHA_INICIO DATE
);

INSERT INTO ORGANIZADOR VALUES
("74625964H","MANUEL INFANTE","47","SUPERVISOR PROFESIONAL","1998-11-30"),
("74636964H","ANDREA RUBIO","47","SUPERVISOR PROFESIONAL","1998-11-30"),
("74647964H","ANTONIO INFANTE","47","SUPERVISOR PROFESIONAL","1998-11-30");

CREATE TABLE DIRECTOR(
	DNI_DIRECTOR CHAR(9) PRIMARY KEY, 
    CV MEDIUMBLOB,
    
    FOREIGN KEY (DNI_DIRECTOR) REFERENCES ORGANIZADOR(DNI)
);

INSERT INTO DIRECTOR VALUES
("74625964H",NULL);

CREATE TABLE CARRERA(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    FECHA DATE, 
    LUGAR_INICIO VARCHAR(100), 
    LUGAR_FIN VARCHAR(100),
    DNI_DIRECTOR CHAR(9),
    
    FOREIGN KEY (DNI_DIRECTOR) REFERENCES DIRECTOR(DNI_DIRECTOR)
);

INSERT INTO CARRERA VALUES
(DEFAULT,"2023-03-16","ARMILLA","SANTA FE","74625964H");

CREATE TABLE CARRERA_PIE(
	ID_CARRERA_PIE INT PRIMARY KEY,
    DESNIVEL FLOAT,
    
    FOREIGN KEY (ID_CARRERA_PIE) REFERENCES CARRERA(ID)
);

CREATE TABLE CARRERA_CICLISTA(
	ID_CARRERA_CICLISTA INT PRIMARY KEY, 
    TEMPERATURA TINYINT UNSIGNED, 
    LLUVIA BOOLEAN,
    
    FOREIGN KEY (ID_CARRERA_CICLISTA) REFERENCES CARRERA(ID)
);

INSERT INTO CARRERA_CICLISTA VALUES
(1,22,TRUE);

CREATE TABLE ETAPA(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NUMERO_ETAPA TINYINT, 
    KM SMALLINT, 
    ID_CARRERA INT,
    
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

INSERT INTO CARRERA_CICLISTA VALUES
(DEFAULT,1,12,1),
(DEFAULT,2,12,1),
(DEFAULT,3,12,1);

CREATE TABLE BICICLETA(
	ID INT PRIMARY KEY, 
    MODELO VARCHAR(50), 
    ELECTRICA BOOLEAN, 
    PESO FLOAT
);

INSERT INTO BICICLETA VALUES
(5466222,"TERRENEITOR",FALSE,10),
(5464722,"DESTRUCTOR",FALSE,9.9);

CREATE TABLE PARTICIPANTE_PARTICIPA_CARRERA(
	DNI_PARTICIPANTE CHAR(9), 
    ID_CARRERA INT, 
    NUMERO_DORSAL SMALLINT,
    
    PRIMARY KEY (DNI_PARTICIPANTE,ID_CARRERA),
    FOREIGN KEY (DNI_PARTICIPANTE) REFERENCES PARTICIPANTE(DNI),
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

 CREATE TABLE ORGANIZADOR_ASISTE_CARRERA(
	DNI_ORGANIZADOR CHAR(9), 
    ID_CARRERA INT,
    
    PRIMARY KEY (DNI_ORGANIZADOR,ID_CARRERA),
    FOREIGN KEY (DNI_ORGANIZADOR) REFERENCES ORGANIZADOR(DNI),
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID)
);

CREATE TABLE CARRERA_CICLISTA_PERMITE_BICICLETA(
	ID_CARRERA_CICLISTA INT, 
    ID_BICICLETA INT,
    
    PRIMARY KEY (ID_CARRERA_CICLISTA,ID_BICICLETA),
    FOREIGN KEY (ID_CARRERA_CICLISTA) REFERENCES CARRERA(ID),
    FOREIGN KEY (ID_BICICLETA) REFERENCES BICICLETA(ID)
);