#PUBLICACION (ISSN, TITULO, NUMERO,AÑO)
#ARTICULO (TITULO, FECHA_INICIO, FECHA_FIN, ISSN_PUBLICACION)
#AUTOR (ID, NOMBRE, E-MAIL, DEPARTAMENTO)
#AUTOR_ESCRIBE_ARTICULO (ID_AUTOR, TITULO_ARTICULO, POSICION)

DROP SCHEMA IF EXISTS ARTICULOS;
CREATE SCHEMA ARTICULOS;
USE ARTICULOS;

CREATE TABLE PUBLICACION(
	ISSN CHAR(8) PRIMARY KEY,
    TITULO VARCHAR(100),
    NUMERO SMALLINT,
    ANIO SMALLINT
);

CREATE TABLE ARTICULO(
	TITULO VARCHAR(100) PRIMARY KEY,
    PAGINA_INICIO SMALLINT,
    PAGINA_FIN SMALLINT,
    ISSN_PUBLICACION CHAR(8),
    
    FOREIGN KEY (ISSN_PUBICACION) REFERENCES PUBLICACION(ISSN)
);

CREATE TABLE AUTOR(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    EMAIL VARCHAR(100),
    DEPARTAMENTO VARCHAR(100)
);

CREATE TABLE AUTOR_ESCRIBE_ARTICULO(		# (ID_AUTOR, TITULO_ARTICULO, POSICION)
	ID_AUTOR INT,
    TITULO_ARTICULO VARCHAR(100),
    POSICION TINYINT,
    
    PRIMARY KEY (ID_AUTOR,TITULO_ARTICULO),

    FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID),
    FOREIGN KEY (TITULO_ARTICULO) REFERENCES ARTICULO(TITULO)
);

INSERT INTO PUBLICACION VALUES		#(ISSN, TITULO, NUMERO,AÑO)
("78952422","El cosmos", "13", 2017);

INSERT INTO ARTICULO VALUES		#(TITULO, PAGINA_INICIO, PAGINA_FIN, ISSN_PUBLICACION)
("El flujo de los escrementos en el espacio","1","21","78952422"),
("¿Por qué no puede orinar ningún animal fuera de gravedad?","22","38","78952422");

INSERT INTO AUTOR VALUES
(DEFAULT,"Franchesco Virgolini","chescoelbesto_contacto@hotmail.com","Ciencia"),
(DEFAULT,"VVito","wito12_contacto@hotmail.com","Ciencia");

INSERT INTO AUTOR_ESCRIBE_ARTICULO VALUES
("1","El flujo de los escrementos en el espacio","1");
