#PELICULA (ID, TITULO, AÑO, NACIONALIDAD, IDIOMA, COLOR, RESTRICCION_EDAD, RESUMEN, OBSERVACIONES)
#ACTOR (ID, NOMBRE, NACIONALIDAD)
#DIRECTOR (ID, NOMBRE, FECHA_NACIMIENTO, PAIS_ORIGEN)
#ACTOR_ACTUA_PELICULA (ID_PELICULA,ID_ACTOR,PERSONAJE)
#DIRECTOR_DIRIGE_PELICULA (ID_DIRECTOR,ID_PELICULA)

DROP SCHEMA IF EXISTS PELICULAS;
CREATE SCHEMA PELICULAS;
USE PELICULAS;

CREATE TABLE PELICULA(
	ID INT PRIMARY KEY AUTO_INCREMENT,	# PONEMOS INT PORQUE SI SE HACEN CALCULOS POR EL AUTOINCREMENT (AUTOMATICMANTE SE SUMA 1)
    TITULO VARCHAR(100),
    ANIO SMALLINT,
    NACIONALIDAD VARCHAR(50),
    IDIOMA VARCHAR(50),
    COLOR BOOLEAN,
    RESTRICCION_EDAD VARCHAR(50),
    RESUMEN TEXT,
    OBSERVACIONES TINYTEXT
);

CREATE TABLE ACTOR(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    NACIONALIDAD VARCHAR(50)
);

CREATE TABLE DIRECTOR(
	 ID INT PRIMARY KEY AUTO_INCREMENT,
     NOMBRE VARCHAR(50),
     FECHA_NACIMIENTO DATE,
     PAIS_ORIGEN VARCHAR(50)
);

CREATE TABLE ACTOR_ACTUA_PELICULA(
	ID_ACTOR INT,
    ID_PELICULA INT,
    PERSONAJE VARCHAR (50),
    
    PRIMARY KEY (ID_ACTOR,ID_PELICULA,PERSONAJE),
    FOREIGN KEY (ID_ACTOR) REFERENCES ACTOR(ID),
    FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID)
);

CREATE TABLE DIRECTOR_DIRIGE_PELICULA(
	ID_DIRECTOR INT,
    ID_PELICULA INT,
    
    PRIMARY KEY (ID_DIRECTOR,ID_PELICULA),
    FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTOR(ID),
    FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID)
);

# UNO DE LOS ACTORES INTERPRETA 3 PERSONAJES EN UNA MISMA PELICULA
# CREA DOS DIRECTORES
# UNA DE LAS PELICULAS ESTA CODIRIGIDA POR LOS 2 DIRECTORES

INSERT INTO ACTOR VALUES
(DEFAULT,"Litri","España"),
(DEFAULT,"Foliulfo","España"),
(DEFAULT,"Paco","España"),
(DEFAULT,"Paca","España");

INSERT INTO DIRECTOR VALUES		
(DEFAULT,"Manuelillo 'el Puro'","1823-08-25","ESPAÑA"),
(DEFAULT,"Manolo Metralleta","1853-02-15","ESPAÑA");

INSERT INTO PELICULA VALUES		
(DEFAULT,"¡Ole!","1943","ESPAÑA!","ESPAÑOH CON DO COHONE",FALSE,"0 pa to la puresa","Que viva ESPAÑAAAAAA","LA PUREZA"),
(DEFAULT,"La vaquilla torera","1982","ESPAÑA!","ESPAÑOH CON DO COHONE",TRUE,"3 año pa la chavaleria que aprenda","No hay na como una corria toro y una vaquilla que torea porque el Litri le enseñó","LA PUREZA 2");

INSERT INTO ACTOR_ACTUA_PELICULA VALUES		
("3","1","Manuelito"),
("4","1","Manolita"),
("1","2","Litri 'El Maetro'"),
("2","2","La Vaquilla toreaora"),
("2","2","El Toro toreao"),
("2","2","La puerta que se abre");

INSERT INTO DIRECTOR_DIRIGE_PELICULA VALUES		
("1","1"),
("2","1");

SELECT*FROM ACTOR_ACTUA_PELICULA;
SELECT*FROM DIRECTOR_DIRIGE_PELICULA;

