DROP SCHEMA IF EXISTS HOSPITAL;
CREATE SCHEMA HOSPITAL;
USE HOSPITAL;

CREATE TABLE ESPECIALISTA(
	NUMERO_COLEGIADO INT PRIMARY KEY, 
    NOMBRE VARCHAR(50),
    ESPECIALIDAD VARCHAR(50)
);

CREATE TABLE PACIENTE(
	NSS CHAR(12) PRIMARY KEY,
    DNI CHAR(9) UNIQUE,
    NOMBRE VARCHAR(50),
    FECHA_NACIMIENTO DATE
);

CREATE TABLE APARATO(
	NOMBRE VARCHAR(50) PRIMARY KEY,
    ELECTRICO BOOLEAN,
    FUNGIBLE BOOLEAN
);

CREATE TABLE PRUEBA(
	CODIGO INT AUTO_INCREMENT,
    NOMBRE_APARATO VARCHAR(50),
    
    PRIMARY KEY (CODIGO,NOMBRE_APARATO),
    FOREIGN KEY (NOMBRE_APARATO) REFERENCES APARATO(NOMBRE)
);

CREATE TABLE HABITACION(
	PLANTA TINYINT,
    NUMERO SMALLINT,
    
    PRIMARY KEY (PLANTA,NUMERO)
);

CREATE TABLE CAMA(
	NUMERO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(50),
    PLANTA_HABITACION TINYINT,
    NUMERO_HABITACION SMALLINT,
    
    FOREIGN KEY (PLANTA_HABITACION,NUMERO_HABITACION) REFERENCES HABITACION(PLANTA,NUMERO)
);

CREATE TABLE ESPECIALISTA_REALIZA_PRUEBA_PACIENTE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NUM_COLEGIADO_ESPECIALISTA INT,
    CODIGO_PRUEBA INT,
    NSS_PACIENTE CHAR(12),
    FECHA_HORA_PRUEBA DATETIME,
    
    UNIQUE (NUM_COLEGIADO_ESPECIALISTA,CODIGO_PRUEBA,NSS_PACIENTE,FECHA_HORA_PRUEBA),
    FOREIGN KEY (NUM_COLEGIADO_ESPECIALISTA) REFERENCES ESPECIALISTA(NUMERO_COLEGIADO),
    FOREIGN KEY (CODIGO_PRUEBA) REFERENCES PRUEBA(CODIGO),
    FOREIGN KEY (NSS_PACIENTE) REFERENCES PACIENTE(NSS)
);

CREATE TABLE PACIENTE_INGRESA_CAMA(
	NSS_PACIENTE CHAR(12),
    NUMERO_CAMA INT,
    FECHA_INGRESO DATE,
    FECHA_ALTA DATE,
    
    PRIMARY KEY (NSS_PACIENTE,NUMERO_CAMA,FECHA_INGRESO),
    FOREIGN KEY (NSS_PACIENTE) REFERENCES PACIENTE(NSS),
    FOREIGN KEY (NUMERO_CAMA) REFERENCES CAMA(NUMERO)
);
