DROP SCHEMA IF EXISTS POKEMON_DATOS;
CREATE SCHEMA POKEMON_DATOS;
USE POKEMON_DATOS;

CREATE TABLE ENTRENADOR(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
	NOMBRE VARCHAR(50), 
	EDAD TINYINT
);

CREATE TABLE GIMNASIO(
	ID INT PRIMARY KEY AUTO_INCREMENT UNIQUE, 
    NOMBRE VARCHAR (50), 
    CIUDAD VARCHAR (50) DEFAULT "CIUDAD ESMERALDA", 
    ID_LIDER INT,
    
    FOREIGN KEY (ID_LIDER) REFERENCES ENTRENADOR(ID)
);

CREATE TABLE POKEMON(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
	NOMBRE VARCHAR(50) NOT NULL, 
    TIPO VARCHAR(30) NOT NULL, 
    NIVEL TINYINT NOT NULL, 
    ID_ENTRENADOR INT, 
    FECHA_CAPTURA DATETIME, 
    POKEBALLS_USADAS TINYINT,
    
    FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID),
    CONSTRAINT LIMITE_POKEBALLS CHECK (POKEBALLS_USADAS BETWEEN 1 AND 5)
);

CREATE TABLE MEDALLA(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    FECHA DATETIME, 
    NOMBRE VARCHAR(50), 
    ID_ENTRENADOR INT, 
    ID_GIMNASIO INT,
    
    FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID),
    FOREIGN KEY (ID_GIMNASIO) REFERENCES GIMNASIO(ID)
);

CREATE TABLE ENTRENADOR_DESAFIA_GIMNASIO(
	ID_ENTRENADOR INT, 
    ID_GIMNASIO INT, 
    FECHA_DESAFIO DATETIME,
    
    PRIMARY KEY (ID_ENTRENADOR, ID_GIMNASIO, FECHA_DESAFIO),
    FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID),
    FOREIGN KEY (ID_GIMNASIO) REFERENCES GIMNASIO(ID)
);

INSERT INTO ENTRENADOR VALUES
(DEFAULT,"ASH KETCHUM", 82),
(DEFAULT,"BROCK", 89),
(DEFAULT,"MISTY", 91);

SELECT*FROM ENTRENADOR;

INSERT INTO GIMNASIO VALUES
(DEFAULT,"GIMNASIO PEDREGAL","CIUDAD PLATEADA",2);

SELECT*FROM GIMNASIO;

INSERT INTO POKEMON VALUES
(DEFAULT,"PIKACHU", "ELECTRICO",100,1,"1902-05-14 16:30:16", 1),
(DEFAULT,"TREECKO", "PLANTA",13,1,"1902-05-14 16:30:16",1),
(DEFAULT,"ONIX", "ROCA",74,2,"1902-05-14 16:30:16",3),
(DEFAULT,"OMASTAR", "ROCA-AGUA",56,2,"1902-05-14 16:30:16",1),
(DEFAULT,"PSYDUCK", "AGUA",68,3,"1902-05-14 16:30:16",5),
(DEFAULT,"STARYU", "AGUA",45,3,"1902-05-14 16:30:16",2);

SELECT*FROM POKEMON;

INSERT INTO MEDALLA VALUES
(DEFAULT,"1902-05-14 16:30:16","MEDALLA ROCA","1",1);

SELECT*FROM MEDALLA;

INSERT INTO ENTRENADOR_DESAFIA_GIMNASIO VALUES
(1,1,"1902-05-14 16:30:16"),
(1,1,"1902-05-15 16:30:16");

SELECT*FROM ENTRENADOR_DESAFIA_GIMNASIO;



