DROP SCHEMA IF EXISTS CAZAFANTASMA;
CREATE SCHEMA CAZAFANTASMA;
USE CAZAFANTASMA;

CREATE TABLE CAZAFANTASMA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    ANOS_EXPERIENCIA TINYINT,	#TAMBIEN PODRIAMOS PONER AQUI 'UNSIGNED' PARA SUPERIOR A 0
    ESPECIALIZACION VARCHAR(100),
    
    CONSTRAINT EXPERIENCIA_MINIMO CHECK(ANOS_EXPERIENCIA>0)
);

CREATE TABLE GRUPO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    FECHA_FORMACION DATE,
    FECHA_DISOLUCION DATE,
    ID_CAZAFANTASMA_LIDER INT,
    
    FOREIGN KEY (ID_CAZAFANTASMA_LIDER) REFERENCES CAZAFANTASMA(ID),
    
    CONSTRAINT FECHA_CORRECION CHECK(FECHA_DISOLUCION > FECHA_FORMACION)
);

CREATE TABLE EQUIPO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DIFICULTAD_USO VARCHAR(30) DEFAULT "MEDIA",
    FOTO MEDIUMBLOB,
    DESCRIPCION MEDIUMTEXT
);

CREATE TABLE PERSONA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE,
    FECHA_DEFUNCION DATE
);

CREATE TABLE FANTASMA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    EDAD SMALLINT,
    TIPO VARCHAR(100),
    DESCRIPCION MEDIUMTEXT,
    ID_PERSONA INT, 
    ID_CAZAFANTASMA INT,
    FECHA_CAPTURA DATE,
    
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID),
    FOREIGN KEY (ID_CAZAFANTASMA) REFERENCES CAZAFANTASMA(ID),
    
    CONSTRAINT EDAD_FANTASMA CHECK (EDAD BETWEEN 1 AND 1000)
);

CREATE TABLE GRUPO_INVESTIGA_FANTASMA(
	ID_GRUPO INT,
    ID_FANTASMA INT,
    
    PRIMARY KEY (ID_GRUPO,ID_FANTASMA),
    FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID),
    FOREIGN KEY (ID_FANTASMA) REFERENCES FANTASMA(ID)
);

CREATE TABLE CAZAFANTASMA_PERTENECE_GRUPO(
	ID_CAZAFANTASMA INT,
    ID_GRUPO INT,
    FUNCION VARCHAR(200),	# HE PUESTO 200 POR SI REALIZA UNA FUNCION CON MUCHOS DETALLES, AUNQUE PODRÍA SER MUCHO MENOS SI HABLAMOS DE FUNCIONES ESTILO 'SOPORTE' O 'ATACANTE'.
    
    PRIMARY KEY(ID_CAZAFANTASMA,ID_GRUPO),
    FOREIGN KEY (ID_CAZAFANTASMA) REFERENCES CAZAFANTASMA(ID),
    FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID)
);

CREATE TABLE CAZAFANTASMA_MANEJA_EQUIPO(
	ID_CAZAFANTASMA INT,
    ID_EQUIPO INT,
    
    PRIMARY KEY (ID_CAZAFANTASMA,ID_EQUIPO),
    FOREIGN KEY (ID_CAZAFANTASMA) REFERENCES CAZAFANTASMA(ID),
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID)
);

CREATE TABLE PERSONA_AVISTA_FANTASMA(
	ID_PERSONA INT,
    ID_FANTASMA INT,
    LUGAR VARCHAR(200),	
    FECHA DATE,	# TENDRIA SENTIDO PONER DATETIME POR FECHA Y HORA DE AVISTAMIENTO PERO COMO SOLO INDICA FECHA EN LA PRUEBA HE PUESTO DATE.
    
    PRIMARY KEY(ID_PERSONA,ID_FANTASMA),
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID),
    FOREIGN KEY (ID_FANTASMA) REFERENCES FANTASMA(ID)
);
