# EJ1 - CREA UN USUARIO system CON CONTRASEÑA 'efd5r26' QUE QUE PUEDA CONECTARSE DESDE CUALQUIER MAQUINA AL SERVIDOR MYSQL 
#       Y QUE TENGA TODOS LOS PRIVILEGIOS SOBRE TODOS LOS OBJETOS DE MYSQL (IGUAL QUE ROOT). TENED EN CUENTA QUE ESTE
#       USUARIO VA A TENER QUE CONCEDER DISTINTOS PRIVILEGIOS A OTROS USUARIOS. 
#     - CREA UNA CONEXION CON EL USUARIO system. HAZ EL RESTO DE APARTADOS USANDO ESTE USUARIO. 

CREATE USER 'system' IDENTIFIED BY '1234';

SELECT user,host FROM mysql.user;

SHOW GRANTS FOR 'system';

GRANT ALL PRIVILEGES ON *.* TO 'system' WITH GRANT OPTION;

SHOW GRANTS FOR 'system';

#============================== TODO ESTO EN 'system' ================================

# EJ2 - CREA USUARIO LLAMADO dependiente_basico CON CONTRASEÑA '1234' QUE PUEDA CONECTARSE DESDE CUALQUIER MAQUINA AL MYSQL.
#     - DALE A dependiente_basico PERMISOS CONSULTA E INSERCION SOBRE LA TABLAS payment, rental Y customer DE LA BASE DE DATOS
#       SAKILA. 
#     - DALE A dependiente_basico PERMISOS PARA QUE EJECUTE TODOS LOS PROCEDIMIENTOS Y FUNCIONES DE LA BASE DE DATOS SAKILA. 

CREATE USER 'dependiente_basico' IDENTIFIED BY '1234';

SELECT user,host FROM mysql.user;

GRANT SELECT, INSERT ON SAKILA.PAYMENT TO 'dependiente_basico';
GRANT SELECT, INSERT ON SAKILA.RENTAL TO 'dependiente_basico';
GRANT SELECT, INSERT ON SAKILA.CUSTOMER TO 'dependiente_basico';

GRANT EXECUTE ON SAKILA.* TO 'dependiente_basico';

SHOW GRANTS FOR 'dependiente_basico';