# EJ2 - CREA USUARIO LLAMADO dependiente_basico CON CONTRASEÑA '1234' QUE PUEDA CONECTARSE DESDE CUALQUIER MAQUINA AL MYSQL.
#     - DALE A dependiente_basico PERMISOS CONSULTA E INSERCION SOBRE LA TABLAS payment, rental Y customer DE LA BASE DE DATOS
#       SAKILA. 
#     - DALE A dependiente_basico PERMISOS PARA QUE EJECUTE TODOS LOS PROCEDIMIENTOS Y FUNCIONES DE LA BASE DE DATOS SAKILA. 

CREATE USER 'dependiente_basico' IDENTIFIED BY '1234';

SELECT user,host FROM mysql.user;	# VER QUE USUARIOS TENEMOS

GRANT SELECT, INSERT ON SAKILA.PAYMENT TO 'dependiente_basico';
GRANT SELECT, INSERT ON SAKILA.RENTAL TO 'dependiente_basico';
GRANT SELECT, INSERT ON SAKILA.CUSTOMER TO 'dependiente_basico';
GRANT EXECUTE ON SAKILA.* TO 'dependiente_basico';

SHOW GRANTS FOR 'dependiente_basico';	# VER QUE PERMISOS TIENE 'X' USUARIO.

# EJ3 - CREA UN USUARIO LLAMADO mto_catalogo CON CONTRASEÑA '5678' QUE PUEDA CONECTARSE DESDE CUALQUIER MAQUINA AL MYSQL.
#     - DALE A mto_catalogo PERMISOS DE INSERCION , MODIFICACION Y BORRADO SOBRE LAS TABLAS film , actor, category, film_actor y 
#       film_text. TAMBIEN PERMISO DE MODIFICACION DE LA ESTRUCTURA DE LAS TABLAS (por ejemplo, para que puedan añadir campos 
#       nuevos) 
#     - CREA UNA CONEXION CON EL USUARIO mto_catalogo Y AÑADE EN CAMPO director (tipo char)  A LA TABLA film DESDE EL USUARIO mto_catalogo 

CREATE USER 'mto_catalogo' IDENTIFIED BY '1234';

GRANT INSERT, ALTER, UPDATE, DELETE ON SAKILA.FILM TO 'mto_catalogo';
GRANT INSERT, ALTER, UPDATE, DELETE ON SAKILA.ACTOR TO 'mto_catalogo';
GRANT INSERT, ALTER, UPDATE, DELETE ON SAKILA.CATEGORY TO 'mto_catalogo';
GRANT INSERT, ALTER, UPDATE, DELETE ON SAKILA.FILM_ACTOR TO 'mto_catalogo';
GRANT INSERT, ALTER, UPDATE, DELETE ON SAKILA.FILM_TEXT TO 'mto_catalogo';

REVOKE DROP ON SAKILA.FILM_TEXT FROM 'mto_catalogo';

SHOW GRANTS FOR 'mto_catalogo';
