# Pablo Jiménez Sánchez

DROP SCHEMA IF EXISTS PT6;
CREATE SCHEMA PT6;
USE PT6;

CREATE TABLE QUIEN(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    EDAD SMALLINT	# HE UTILIZADO SMALLINT PORQUE EL GRINCH PUEDE SER SUPER LONGEVO (CREO), SI NO HUBIERA USADO TINYINT
);

CREATE TABLE GRINCH(
	ID_GRINCH INT PRIMARY KEY,
    NOMBRE_MASCOTA CHAR(3) DEFAULT "MAX",
    COLOR_PELO CHAR(5) DEFAULT "VERDE",
    
    FOREIGN KEY (ID_GRINCH) REFERENCES QUIEN(ID)
);

CREATE TABLE VALLEQUIEN(
	ID_VALLEQUIEN INT PRIMARY KEY,
    DIRECCION VARCHAR(50),
    OFICIO VARCHAR(50),
    
    FOREIGN KEY (ID_VALLEQUIEN) REFERENCES QUIEN(ID)
);

CREATE TABLE REGALO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    PRECIO MEDIUMINT
);

CREATE TABLE OBJETO(
	ID_OBJETO INT PRIMARY KEY,
    PESO DECIMAL(5,2),
    MATERIAL VARCHAR(50),
    
    FOREIGN KEY (ID_OBJETO) REFERENCES REGALO(ID)
);


CREATE TABLE EXPERIENCIA(
	ID_EXPERIENCIA INT PRIMARY KEY,
    DURACION INT,	# HE PUESTO INT PUESTO QUE NO SE SABE CUANTAS HORAS PUEDE LLEGAR A DURAR LA EXPERIENCIA Y PUEDE SER MUY VARIABLE
    UBICACION VARCHAR(50),
    FECHA_CADUCIDAD DATE,
    
    FOREIGN KEY (ID_EXPERIENCIA) REFERENCES REGALO(ID)
);

CREATE TABLE ELECTRONICA(
	ID_ELECTRONICA INT PRIMARY KEY,
    BATERIA BOOLEAN,
    
    FOREIGN KEY (ID_ELECTRONICA) REFERENCES REGALO(ID)
);

CREATE TABLE JUGUETE_PERRO(
	ID_JUGUETE_PERRO INT PRIMARY KEY,
    TAMANIO VARCHAR(50),	# AQUIE HE OPTADO POR VARCHAR PUESTO QUE SE PUEDE DAR SU TAMAÑO COMO: 20cm largo x 5cm ancho
    DURABILIDAD VARCHAR(50),
    
    FOREIGN KEY (ID_JUGUETE_PERRO) REFERENCES REGALO(ID)
);

CREATE TABLE GRINCH_COMPRA_JUGUETE_PERRO(
	ID_GRINCH INT,
    ID_JUGUETE_PERRO INT,
    
    PRIMARY KEY (ID_GRINCH,ID_JUGUETE_PERRO),
    FOREIGN KEY (ID_GRINCH) REFERENCES GRINCH(ID_GRINCH),
    FOREIGN KEY (ID_JUGUETE_PERRO) REFERENCES JUGUETE_PERRO(ID_JUGUETE_PERRO)
);

CREATE TABLE VALLEQUIEN_RECIBE_REGALO(
	ID_VALLEQUIEN_REGALO INT,
    ID_REGALO INT,
    FECHA_HORA DATETIME,
    
    PRIMARY KEY (ID_VALLEQUIEN_REGALO,ID_REGALO,FECHA_HORA),
    FOREIGN KEY (ID_VALLEQUIEN_REGALO) REFERENCES VALLEQUIEN(ID_VALLEQUIEN),
    FOREIGN KEY (ID_REGALO) REFERENCES REGALO(ID)
);

CREATE TABLE GRINCH_ROBA_VALLEQUIEN_RECIBE_REGALO(
	ID_ROBO INT PRIMARY KEY AUTO_INCREMENT,
	ID_GRINCH INT,
    ID_VALLEQUIEN_REGALO INT,
    ID_REGALO INT,
    FECHA_HORA_ROBO DATETIME,
    
    FOREIGN KEY (ID_GRINCH) REFERENCES GRINCH(ID_GRINCH),
    FOREIGN KEY (ID_VALLEQUIEN_REGALO,ID_REGALO,FECHA_HORA_ROBO) REFERENCES VALLEQUIEN_RECIBE_REGALO(ID_VALLEQUIEN_REGALO,ID_REGALO,FECHA_HORA)
);

INSERT INTO QUIEN VALUES
(DEFAULT,"GRINCH",2000),
(DEFAULT, "PABLO",25),
(DEFAULT, "TAMARA", 25),
(DEFAULT, "FERNANDO", 40);

INSERT INTO GRINCH VALUES
(1,DEFAULT,DEFAULT);

INSERT INTO VALLEQUIEN VALUES
(2, "CALLE DELFIN","INFORMATICO"),
(3, "CALLE TRUCHA", "PROFESORA"),
(4, "CALLE TIBURON", "DISEÑADOR GRAFICO");

INSERT INTO REGALO VALUES
(DEFAULT,"FIGURA",30),
(DEFAULT, "VIAJE AL CARIBE",3000),
(DEFAULT, "PC", 2000),
(DEFAULT, "HUESO", 10),
(DEFAULT, "PALO", 5);

INSERT INTO OBJETO VALUES
(1,150.00,"VINILO");

INSERT INTO EXPERIENCIA VALUES
(2,300,"CARIBE","2024-04-10");

