USE SAKILA;

SELECT * FROM FILM;

SELECT * FROM FILM_ACTOR;

SELECT * FROM FILM_CATEGORY;

# EJ1.- ¿CUÁLES SON LAS TARIFAS DE ALQUILER (RENTAL RATE)?
SELECT DISTINCT RENTAL_RATE FROM FILM;

# EJ2.- ¿CUÁNTAS PELÍCULAS DURAN MÁS DE 100 MINUTOS Y TIENEN UN RATING DE PG, R O G?
SELECT COUNT(*) FROM FILM WHERE RATING IN ("PG","R","G") AND LENGTH > 100;

# EJ3.- ¿CUÁL ES LA PELÍCULA O PELÍCULAS CON MAYOR DURACIÓN DE LAS QUE CONTIENEN TRAILERS COMO EXTRAS?
SELECT TITLE FROM FILM WHERE SPECIAL_FEATURES LIKE "%TRAILERS%" AND LENGTH = (SELECT MAX(LENGTH) FROM FILM WHERE SPECIAL_FEATURES LIKE "%TRAILERS%");

# EJ4.- ¿QUÉ PELÍCULAS ESTÁN PROTAGONIZADAS POR UN ASTRONAUTA Y UN ADMINSTRADOR DE BASES DE DATOS (DESCRIPTION)?
SELECT TITLE FROM FILM WHERE DESCRIPTION LIKE "%ASTRONAUT%" AND DESCRIPTION LIKE "%DATABASE ADMINISTRATOR%";

# EJ5.- ¿CUÁNTO DURAN, DE MEDIA, LAS PELÍCULAS PROTAGONIZADAS POR EL ACTOR 1 (FILM_ACTOR)?
SELECT AVG(LENGTH) FROM FILM WHERE FILM_ID IN (SELECT FILM_ID FROM FILM_ACTOR WHERE ACTOR_ID = 1);

# EJ6.- ¿CUÁNTO TARDARÍAMOS (EN HORAS) EN VER TODAS LAS PELÍCULAS DE CATEGORÍA 6 (FILM_CATEGORY)?
SELECT SUM(LENGTH/60) AS DURACION_TOTAL_EN_HORAS FROM FILM WHERE FILM_ID IN (SELECT FILM_ID FROM FILM_CATEGORY WHERE CATEGORY_ID = 6);