# Pablo Jiménez Sánchez

DROP SCHEMA IF EXISTS COMPETICION;
CREATE SCHEMA COMPETICION;
USE COMPETICION;

CREATE TABLE INTEGRANTE(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50), 
    EDAD TINYINT, 
    SALARIO MEDIUMINT, 
    NOMBRE_EQUIPO VARCHAR(50)
);

CREATE TABLE MECANICO(
	ID_MECANICO INT PRIMARY KEY, 
    HORAS_FORMACION MEDIUMINT, 
    FUNCION VARCHAR(50),
    
    FOREIGN KEY (ID_MECANICO) REFERENCES INTEGRANTE(ID)
);

CREATE TABLE INGENIERO(
	ID_INGENIERO INT PRIMARY KEY, 
    AÑOS_EXPERIENCIA TINYINT, 
    ROL VARCHAR(50),
    
    FOREIGN KEY (ID_INGENIERO) REFERENCES INTEGRANTE(ID)
);

CREATE TABLE PILOTO(
	ID_PILOTO INT PRIMARY KEY, 
    TITULOS_CAMPEON SMALLINT, # No he puesto TINYINT porque nunca se sabe que tremendo loco puede haber por ahí en la historia.
    CARRERAS_GANADAS SMALLINT, 
    POLES_LOGRADAS SMALLINT
);

CREATE TABLE EQUIPO(
	NOMBRE VARCHAR(50) PRIMARY KEY, 
    MOTOR VARCHAR(50), 
    PATROCINADOR_PRINCIPAL VARCHAR(50), 
    ID_INTEGRANTE_DIRECTOR INT,
    
    FOREIGN KEY (ID_INTEGRANTE_DIRECTOR) REFERENCES INTEGRANTE(ID)
);
ALTER TABLE INTEGRANTE ADD FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES EQUIPO(NOMBRE);

 CREATE TABLE TEMPORADA(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    ANIO SMALLINT, 
    FECHA_INICIO DATE, 
    FECHA_FIN DATE
);

CREATE TABLE GRAN_PREMIO(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50), 
    CIRCUITO VARCHAR(50), 
    FECHA_HORA_CARRERA DATETIME
);
CREATE TABLE COCHE(
	ID INT PRIMARY KEY AUTO_INCREMENT, 
    PESO FLOAT, # Habia pensado en poner SMALLINT pero es probable que en competiciones así haga falta mucha precisión en los pesos.
    ACELERACION_MAXIMA SMALLINT, 
    ID_INGENIERO INT, 
    ID_PILOTO INT,
    
    FOREIGN KEY (ID_INGENIERO) REFERENCES INGENIERO(ID_INGENIERO),
    FOREIGN KEY (ID_PILOTO) REFERENCES PILOTO(ID_PILOTO)
);

CREATE TABLE MECANICO_MANTIENE_COCHE(
	ID_MECANICO INT, 
    ID_COCHE INT,
    
    PRIMARY KEY (ID_MECANICO,ID_COCHE),
    FOREIGN KEY (ID_MECANICO) REFERENCES MECANICO(ID_MECANICO),
    FOREIGN KEY (ID_COCHE) REFERENCES COCHE(ID)
);

CREATE TABLE EQUIPO_PARTICIPA_TEMPORADA(
	NOMBRE_EQUIPO VARCHAR(50), 
    ID_TEMPORADA INT,
    
    PRIMARY KEY (NOMBRE_EQUIPO,ID_TEMPORADA),
    FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES EQUIPO(NOMBRE),
    FOREIGN KEY (ID_TEMPORADA) REFERENCES TEMPORADA(ID)
);

CREATE TABLE TEMPORADA_DIVIDE_GRAN_PREMIO(
	ID_TEMPORADA INT, 
    ID_GRAN_PREMIO INT,
    
    PRIMARY KEY (ID_TEMPORADA,ID_GRAN_PREMIO),
    FOREIGN KEY (ID_TEMPORADA) REFERENCES TEMPORADA(ID),
	FOREIGN KEY (ID_GRAN_PREMIO) REFERENCES GRAN_PREMIO(ID)
);

CREATE TABLE PILOTO_COMPITE_GRAN_PREMIO(
	ID_PILOTO INT, 
    ID_GRAN_PREMIO INT,
    
	PRIMARY KEY (ID_PILOTO,ID_GRAN_PREMIO),
	FOREIGN KEY (ID_PILOTO) REFERENCES PILOTO(ID_PILOTO),
    FOREIGN KEY (ID_GRAN_PREMIO) REFERENCES GRAN_PREMIO(ID)
);