USE SAKILA;

SELECT * FROM FILM;

SELECT * FROM ACTOR;

SELECT * FROM FILM_ACTOR;

# EJ.1- MUESTRA LA PELICULA MAS LARGA
SELECT TITLE,LENGTH FROM FILM WHERE LENGTH = (SELECT MAX(LENGTH) FROM FILM);

# EJ.2- MUESTRA LA PELICULA CON MENOR DURACION
SELECT TITLE,LENGTH FROM FILM WHERE LENGTH = (SELECT MIN(LENGTH) FROM FILM);

# EJ.3- MUESTRA LOS DISTINTOS RATING DE EDAD USADOS
SELECT DISTINCT RATING FROM FILM;

# EJ.4- CUANTAS PELICULAS DURAN MAS DE 2 HORAS
SELECT COUNT(*) AS PELICULAS_DURACION_MAS_2_HORAS FROM FILM WHERE LENGTH > 120;

# EJ.5- MUESTRA EL NOMBRE DE LA PELICULAS Y SU DURACION EN HORAS
SELECT TITLE,LENGTH/60 AS DURACION_HORAS FROM FILM;

# EJ.6- CUANTAS PELICULAS CONTIENEN ESCENAS ELIMINADAS?
SELECT COUNT(*) FROM FILM WHERE SPECIAL_FEATURES LIKE "%DELETED SCENES%";

# EJ.7- QUE PELICULAS TIENEN "ALIEN" EN SU NOMBRE?
SELECT TITLE FROM FILM WHERE TITLE LIKE "%ALIEN%" ORDER BY TITLE;

# EJ.8- CUAL ES LA PELICULA MÁS LARGA QUE PODEMOS VER POR MENOS DE 1$ (RENTAL_RATE)
SELECT * FROM FILM WHERE RENTAL_RATE < 1 AND LENGTH = (SELECT MAX(LENGTH) FROM FILM WHERE RENTAL_RATE < 1);

# ***EJ.9- CUANTAS PELICULAS SON DOCUMENTALES? (COLUMNA DESCRIPTION)
SELECT COUNT(*) FROM FILM WHERE DESCRIPTION LIKE "%DOCUMENTARY%";

# EJ.10- CUAL ES EL PRECIO DE REEMPLAZO MEDIO DE LAS PELICULAS CON RATING "R"
SELECT AVG(REPLACEMENT_COST) FROM FILM WHERE RATING = "R";

# EJ.11- CUANTOS DIAS TARDARÍAMOS EN VER TODAS LAS PELICULAS? Y AÑOS?
SELECT SUM(LENGTH)/60/24 FROM FILM;

SELECT SUM(LENGTH)/60/24/365 FROM FILM;

# EJ.12 MUESTRA LOS PRECIOS DE ALQUILER (RENTAL_RATE) Y CUANTAS PELICULAS SE ALQUILAN DE CADA PRECIO
SELECT RENTAL_RATE, COUNT(*) FROM FILM GROUP BY RENTAL_RATE;

# EJ.13 MUESTRA LA DURACION MEDIA DE LAS PELICULAS AGRUPADAS POR RATING
SELECT ROUND(AVG(LENGTH)) AS DURACION_MEDIA, RATING FROM FILM GROUP BY RATING;

# EJ.14 MUESTRA LA DURACION MEDIA DE LAS PELICULAS SIN ESCENAS ELIMINADAS AGRUPADAS POR RATING
SELECT ROUND(AVG(LENGTH)) AS DURACION_MEDIA, RATING FROM FILM WHERE SPECIAL_FEATURES NOT LIKE "%DELETED SCENES%" GROUP BY RATING;

# EJ.15 ¿CUANTO COSTARÍA REEMPLAZAR (REPLACEMENT_COST) LAS PELICULAS DE JENNIFER DAVIS (TABLA ACTOR Y FILM_ACTOR) SI VAMOS AL VIDEOCLUB Y LAS DESTRUIMOS?
SELECT SUM(REPLACEMENT_COST) AS COSTE_REEMPLAZO_JD FROM FILM WHERE FILM_ID IN (SELECT FILM_ID FROM FILM_ACTOR WHERE ACTOR_ID = (SELECT ACTOR_ID FROM ACTOR WHERE FIRST_NAME = "JENNIFER" AND LAST_NAME = "DAVIS"));

# EJ.16 MUESTRA EL NOMBRE DE LAS PELÍCULAS EN MINÚSCULAS
SELECT LOWER(TITLE) AS NOMBRE_MINÚSCULA FROM FILM;