# EJ1 - ¿CUANTOS DIAS HAS VIVIDO?
SELECT DATEDIFF(NOW(), "1998-03-13") AS DIAS_VIVIDOS;

# EJ2 - ¿CUANTAS HORAS HAS VIVIDO?
SELECT TIMESTAMPDIFF(HOUR, "1998-03-13", NOW()) AS HORAS_VIVIDAS;

# EJ3 - ¿QUE DIA DE LA SEMANA NACISTE?
SELECT TIMESTAMPDIFF(HOUR, "1998-03-13", NOW()) AS HORAS_VIVIDAS; 

# EJ4 - ¿QUE EDAD TENIAS EL 1 DE ENERO DEL AÑO 2000?
SELECT FLOOR(DATEDIFF("2000-01-01","1998-03-13")/365) AÑOS_ENERO_2000;

# EJ5 - ¿EN QUE FECHA ESTAREMOS DENTRO DE 7000 HORAS?
SELECT DATE_ADD(NOW(), INTERVAL 7000 HOUR);

# EJ6 - ¿EN QUE FECHA DUPLICARAS TU EDAD?
SELECT DATE_ADD(NOW(), INTERVAL (SELECT DATEDIFF(NOW(), "1998-03-13")) DAY);

# EJ7 - MUESTRA LOS DIAS QUE HAN ALQUILADO LAS PELICULAS (RENTAL).
USE SAKILA;

SELECT
	RENTAL_ID,
    RENTAL_DATE,
    RETURN_DATE,
    DATEDIFF(RETURN_DATE, RENTAL_DATE) AS DIAS_ALQUILER
FROM RENTAL;

# EJ8 - MUESTRA UNA LISTA DE LOS TITULOS DE PELICULAS Y CUANTOS DIAS DE MEDIA SE HAN ALQUILADO.
SELECT * FROM RENTAL;
SELECT * FROM INVENTORY;
SELECT * FROM CUSTOMER;

SELECT
	FILM.TITLE,
   AVG( DATEDIFF(RENTAL.RETURN_DATE, RENTAL.RENTAL_DATE)) AS DIAS_ALQUILER_PROMEDIO
FROM RENTAL
JOIN INVENTORY ON RENTAL.INVENTORY_ID = INVENTORY.INVENTORY_ID
JOIN FILM ON INVENTORY.FILM_ID = FILM.FILM_ID
GROUP BY FILM.FILM_ID;

# EJ9 - MUESTRA UNA LISTA CON EL ID DEL ALQUILER, EL NOMBRE COMPLETO DEL CLIENTE, EL NOMBRE DE LA PELICULA Y CUANTAS VECES HA PODIDO VER LA PELICULA EN ESOS DIAS.
SELECT
	RENTAL.RENTAL_ID,
    CONCAT(CUSTOMER.FIRST_NAME,"-",CUSTOMER.LAST_NAME) AS CLIENTE,
	FILM.TITLE,
    ROUND(DATEDIFF(RENTAL.RETURN_DATE, RENTAL.RENTAL_DATE)*24*60/FILM.LENGTH, 2) AS VECES_VISTA
FROM RENTAL
JOIN INVENTORY ON RENTAL.INVENTORY_ID = INVENTORY.INVENTORY_ID
JOIN CUSTOMER ON INVENTORY.STORE_ID = CUSTOMER.STORE_ID
JOIN FILM ON INVENTORY.FILM_ID = FILM.FILM_ID;

# EJ10 - MUESTRA UNA LISTA DE LOS CLIENTES Y EL TOTAL DE DÍAS QUE HAN TENIDO PELÍCULAS ALQUILADAS
SELECT
    CONCAT(CUSTOMER.FIRST_NAME,"-",CUSTOMER.LAST_NAME) AS CLIENTE,
    SUM(DATEDIFF(RENTAL.RETURN_DATE, RENTAL.RENTAL_DATE)) AS DIAS_PELICULEANDO
FROM RENTAL
JOIN CUSTOMER ON RENTAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
GROUP BY CUSTOMER.CUSTOMER_ID;

# EJ11 - MUESTRA UNA LISTA CON EL ID DEL ALQUILER, EL NOMBRE COMPLETO DEL CLIENTE, EL NOMBRE DE LA PELÍCULA, LA FECHA DE ALQUILER, LA FECHA DE DEVOLUCIÓN Y LA FECHA DE PAGO (SOLO FECHA EN TODOS LOS CASOS)
SELECT
	RENT.RENTAL_ID,
    CONCAT(CUST.FIRST_NAME,"-",CUST.LAST_NAME) AS CLIENTE,
	FILM.TITLE AS PELICULA,
    DATE(RENTAL_DATE) AS FECHA_ALQUILER,
    DATE(RETURN_DATE) AS FECHA_DEVOLUCION,
    DATE(PAYMENT_DATE) AS FECHA_PAGO
FROM RENTAL RENT
JOIN INVENTORY INV ON RENT.INVENTORY_ID = INV.INVENTORY_ID
JOIN FILM ON INV.FILM_ID = FILM.FILM_ID
JOIN CUSTOMER CUST ON RENT.CUSTOMER_ID = CUST.CUSTOMER_ID
JOIN PAYMENT PAY ON RENT.RENTAL_ID = PAY.RENTAL_ID;

# EJ12 - ¿CUÁNTAS PELÍCULAS SE HAN ALQUILADO ENTRE LAS 12 DE LA NOCHE Y LAS 6 DE LA MAÑANA?
SELECT 
	COUNT(*) AS "Películas alquiladas entre las 12 de la noche y las 6 de la mañana"
FROM RENTAL 
WHERE TIME(RENTAL_DATE)>="00:00:00" AND TIME(RENTAL_DATE)<="06:00:00";
#WHERE HOUR(RENTAL_DATE)>=0 AND HOUR(RENTAL_DATE)<=5;

# EJ13 - MUESTRA LA CANTIDAD DE SINIESTROS QUE HAN OCURRIDO PARA CADA DÍA DE LA SEMANA. ORDENA DE MAYOR A MENOR.
USE SEGUROS;

SELECT
    DATE_FORMAT(FECHA, "%W") AS DIA_SEMANA,
    COUNT(*) AS SINIESTROS
FROM SINIESTRO
GROUP BY DIA_SEMANA
ORDER BY SINIESTROS;

# EJ14 - MUESTRA SOLO LOS CLIENTES QUE LLEVEN MÁS DE UN AÑO CON EL PERMISO DE CONDUCIR.
SELECT 
	*
FROM CLIENTE
WHERE FECHA_PERMISO < DATE_ADD(NOW(), INTERVAL -1 YEAR);

# EJ15 - MUESTRA SOLO LOS CLIENTES QUE LLEVEN MÁS DE UN AÑO CON EL PERMISO DE CONDUCIR Y TIENEN MÁS DE 25 AÑOS.
SELECT 
	*
FROM CLIENTE
WHERE FECHA_PERMISO < DATE_ADD(NOW(), INTERVAL -1 YEAR) AND FECHA_NACIMIENTO < DATE_ADD(NOW(), INTERVAL -25 YEAR);

# EJ16 - ¿HAY ALGÚN CLIENTE CUYA FECHA DE NACIMIENTO SEA POSTERIOR A LA FECHA DE MATRICULACIÓN DE SU VEHÍCULO?
SELECT 
	CLI.DNI,
    CLI.NOMBRE
FROM CLIENTE CLI
JOIN CLIENTE_ASEGURA_VEHICULO CAV ON CLI.DNI = CAV.DNI_CLIENTE
JOIN VEHICULO VEH ON CAV.NUMERO_BASTIDOR_VEHICULO = VEH.NUMERO_BASTIDOR
WHERE CLI.FECHA_NACIMIENTO > VEH.FECHA_1_MATRICULACION
GROUP BY CLI.DNI
ORDER BY CLI.NOMBRE;

# EJ17 - MUESTRA LA TABLA DE CLIENTES COMPLETA Y AÑADE UNA COLUMNA BOOLEANA QUE INDIQUE SI EL CLIENTE ERA MAYOR DE EDAD O NO CUANDO SE SACÓ EL PERMISO.
SELECT 
	*,
    FECHA_PERMISO > DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL 18 YEAR) AS "Mayor de edad al conseguir el permiso."
FROM CLIENTE CLI;

# EJ18 - MUESTRA LA TABLA DE CLIENTES COMPLETA Y AÑADE UNA COLUMNA QUE INDIQUE: La Organización Mundial de la Salud (OMS), por su parte, clasifica la edad adulta de la siguiente manera: adulto joven, de 18 a 44 años; adulto medio, de 45 a 59 años; adulto mayor (o anciano joven), de 60 a 74 años; anciano, de 75 a 90 años; y anciano longevo, a partir de los 90 años.
SELECT 
	*,
    DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL NOW() YEAR) AS EDAD,
    CASE
		WHEN  EDAD >= DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL 18 YEAR) AND EDAD <= DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL 44 YEAR) THEN "adulto joven"
        WHEN  EDAD >= DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL 45 YEAR) AND EDAD <= DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL 59 YEAR) THEN "adulto medio"
        WHEN  EDAD >= DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL 60 YEAR) AND EDAD <= DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL 74 YEAR) THEN "adulto mayor"
        WHEN  EDAD >= DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL 75 YEAR) AND EDAD <= DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL 90 YEAR) THEN "anciano"
        WHEN  EDAD > DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL 90 YEAR) THEN "anciano longevo"
	END AS "La Organización Mundial de la Salud (OMS), por su parte, clasifica la edad adulta de la siguiente manera:"
FROM CLIENTE CLI;

SELECT 
	*,
    DATE_ADD(CLI.FECHA_NACIMIENTO, INTERVAL NOW() YEAR) AS EDAD
FROM CLIENTE CLI;


# EJ19 - MUESTRA LA TABLA DE CLIENTES COMPLETA Y AÑADE UNA COLUMNA QUE INDIQUE "CONDUCTOR TARDÍO" SI EL CLIENTE TARDÓ MÁS DE 10 AÑOS TRAS SU MAYORÍA DE EDAD EN OBTENER EL PERMISO DE CONDUCIR O "CONDUCTOR PRECOZ" EN CASO CONTRARIO.

# EJ20 - MUESTRA LA TABLA DE SINIESTROS COMPLETA PERO AÑADIENDO UNA COLUMNA BOOLEANA QUE INDIQUE SI EL SINIESTRO OCURRIÓ EN FIN DE SEMANA O NO.

# EJ21 - MUESTRA EL NOMBRE DE LOS PAÍSES Y SU ESPERANZA DE VIDA. PARA LOS PAÍSES SIN ESPERANZA DE VIDA, MUESTRA LA MEDIA DE ESPERANZA DE VIDA MUNDIAL.

# EJ22 - MUESTRA EL NOMBRE DE LOS PAÍSES, SU AÑO DE INDEPENDENCIA Y UNA COLUMNA QUE INDIQUE "DESCOLONIZACIÓN" SI LA FECHA DE INDEPENDENCIA ES POSTERIOR O IGUAL A 1945 O "-" EN CASO CONTRARIO.