# ESTA ES LA FECHA Y HORA DEL SERVIDOR.
SELECT NOW(); 
# HACE LO MISMO QUE LA DE ARRIBA.
SELECT CURRENT_TIMESTAMP(); 	

# DA LA FECHA SOLO.
SELECT CURRENT_DATE(); 	
# DA LA HORA.
SELECT CURRENT_TIME(); 

# DIFERENCIA EN DIAS ENTRE DOS FECHAS.
SELECT DATEDIFF("2017-06-25", "2017-06-15");	

# AÑADIR INTERVALOS A UNA FECHA Y HORA.
SELECT DATE_ADD("2017-06-25", INTERVAL 10 DAY);
SELECT DATE_ADD("2017-06-25", INTERVAL 10 YEAR);
SELECT DATE_ADD("2017-06-25", INTERVAL 10 HOUR);
SELECT DATE_ADD("2017-06-25", INTERVAL 10 WEEK);
SELECT DATE_ADD("2017-06-25", INTERVAL 100000 SECOND);

# EXTRAER PARTES DE UNA FECHA 
SELECT DAY(NOW());
SELECT EXTRACT(DAY FROM NOW());

SELECT MONTH(NOW());
SELECT YEAR(NOW());
SELECT MINUTE(NOW());
SELECT HOUR(NOW());
SELECT SECOND(NOW());

# FORMATEAR FECHAS.
SELECT CONCAT(YEAR(NOW()),"-",MONTH(NOW()));
SELECT DATE_FORMAT(NOW(), "%e del %c de %Y");
SELECT DATE_FORMAT(NOW(), "%u");

# ALGUNAS FUNCIONES AVANZADAS
USE WORLD; 

# ES UN IF ELSE
SELECT IF(500<1000, "YES", "NO");

SELECT
	NAME,
    REGION,
    POPULATION,
	IF(POPULATION>100000, NAME, REGION)
FROM COUNTRY;

SELECT IFNULL(NULL, "W3Schools.com");

# INTERCAMBIA POR EL VALOR DADO LOS VALORES NULL QUE HAYA
SELECT
	NAME,
    INDEPYEAR,
    IFNULL(INDEPYEAR, "LA BEBESITA BEBE LIN Y BEBE WHIKI FUMA MARIGUANA Y TAMBIEN SE METE PIKI")
	# IF(INDEPYEAR IS NULL, "LA BEBESITA...", INDEPYEAR);	// TAMBIEN SE PUEDE HACER ASI
FROM COUNTRY;

# SELECCIONA EL PRIMER VALOR NO NULO
SELECT COALESCE(NULL, NULL, NULL, 'W3Schools.com', NULL, 'Example.com');

SELECT
	NAME, INDEPYEAR, GNPOLD, LOCALNAME,
    COALESCE(INDEPYEAR, GNPOLD, LOCALNAME)
FROM COUNTRY;

# FUNCION CASE
# La sentencia CASe recorre las condiciones y devuelve un valor cuando le cumple la primera condición(como sentencia IF-THEN-ELSE). Así una vez se cumple la sentencia devuelve el valor y termina de recorrer.
SELECT
	NAME,
    POPULATION,
    CASE
		WHEN POPULATION < 100000 THEN "PAÍS PEQUEÑO"
        WHEN POPULATION < 1000000 THEN "PAÍS MEDIANO"
        WHEN POPULATION < 10000000 THEN "PAÍS GRANDE"
        WHEN POPULATION > 10000000 THEN "PAÍS GIGANTE"
        ELSE "PAÍS MINUSCULO"
	END AS TAMAÑO
FROM COUNTRY;


